5.Rails-Practices-Work/rails-esbuld-setup/config/routes.rb
Rails.application.routes.draw do
  
  # pages routes
  # Defines the root path route ("/")
  root "pages#index"

  # pages routes
  get "about",        to: "pages#about"
  get "services",     to: "pages#services"
  get "contact",      to: "pages#contact"
  get "testimonials", to: "pages#testimonials"
  get "privacy",      to: "pages#privacy"


  # user routes
  # resources :users, only: %i[new create show]
  get "user/index", to: "user#index"
  get "user/new", to: "user#new"
  post "user/create", to: "user#create"
  get "user/:id", to: "user#show", as: "user_show"
  get "user/:id/edit", to: "user#edit", as: "user_edit"
  patch "user/:id", to: "user#update", as: "user_update"
  delete "user/:id", to: "user#destroy", as: "user_delete"
  get "user/search", to: "user#search", as: "user_search"
  
  # signup routes
  get "signup", to: "users#signup", as: "user_signup"
  post "signup", to: "user#create"

end

5.Rails-Practices-Work/rails-esbuld-setup/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

5.Rails-Practices-Work/rails-esbuld-setup/app/models/user.rb
class User < ApplicationRecord
    # table name prefixing
    # self.table_name = 'app_users'

    # set the primary key
    # self.primary_key = 'user_id'

    # set callbacks
    before_save { self.email = email.downcase }
    after_create :log_new_user

    private
    def log_new_user
        Rails.logger.info "New user created: #{self.name} (#{self.email})"
    end

    # validations
    validates :name, presence: true, length: { maximum: 50 }
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, presence: true, length: { maximum: 255 },
                      format: { with: VALID_EMAIL_REGEX },
                      uniqueness: { case_sensitive: false }
    

end

5.Rails-Practices-Work/rails-esbuld-setup/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

5.Rails-Practices-Work/rails-esbuld-setup/app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end

  def about
  end

  def services
  end

  def contact
  end

  def testimonials
  end

  def privacy
  end
end

5.Rails-Practices-Work/rails-esbuld-setup/app/controllers/user_controller.rb
class UserController < ApplicationController
    def signup
    end

    def index
        if params[:q].present?
            query = params[:q]
            @users = User.where("name LIKE ? OR email LIKE ?", "%#{query}%", "%#{query}%")
            respond_to do |format|
                format.html
                format.json {
                    render json: { status: 'SUCCESS', message: 'Loaded all users', data: @users }, status: :ok
                }
            end

        # render :index
        else
            @users = User.all
            respond_to do |format|
                format.html
                format.json {
                    render json: { status: 'SUCCESS', message: 'Loaded all users', data: @users }, status: :ok
                }
            end
        end


           
        # to pass data in json format
        # @users = User.all
        # if @user.present?
        #     render json: {status: 'SUCCESS', message: 'Loaded all users', data: @user}, status: :ok
        # else
        #     render json: {status: 'ERROR', message: 'No users found'}, status: :not_found
        # end
    end

    def new
        @user = User.new
        render "create"  # render "create" view
    end

    def create
        @user = User.new(user_params)
        # return user_params   # to see the form passed params
        if @user.save
            redirect_to user_index_path, notice: "User successfully created."
        else
            flash.now[:alert] = "Error creating user."
            redirect_to user_index_path, status: :unprocessable_entity
        end
    end

    def show
        # find specific user by id
        @user = User.find(params[:id])
        if @user.present?
            render :show, notice: "User details loaded."
        else
            render :index, alert: "User not found."
        end
    end

    def edit
        @user = User.find(params[:id])
    end 

    def update
        @user = User.find(params[:id])
        if @user.update(user_params)
            redirect_to user_show_path(@user), notice: "User successfully updated."
        else
            render :edit
        end
    end

    private
    def user_params
        params.require(:user).permit(:name, :email, :password, :confirm_pass, :is_active)
    end

    def destroy
        @user = User.find(params[:id])
        if @user.destroy
            redirect_to user_index_path, notice: "User successfully deleted."
        else
            redirect_to user_index_path, alert: "Error deleting user."
        end
    end


    # def search
    #     query = params[:query]
    #     @users = User.where("name LIKE ? OR email LIKE ?", "%#{query}%", "%#{query}%")
    #     if @users.empty?
    #         flash.now[:alert] = "No users found matching '#{query}'."
    #     end
    #     render :index
    # end


end

5.Rails-Practices-Work/rails-esbuld-setup/app/helpers/application_helper.rb
module ApplicationHelper
end

5.Rails-Practices-Work/rails-esbuld-setup/app/helpers/pages_helper.rb
module PagesHelper
end

5.Rails-Practices-Work/rails-esbuld-setup/app/helpers/user_helper.rb
module UserHelper
end

5.Rails-Practices-Work/rails-esbuld-setup/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Rails Esbuld Setup" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="application-name" content="Rails Esbuld Setup">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", type: "module" %>
  </head>

  <body>
    <%= render "layouts/partials/navbar" %>
      <%= yield %>

      <%# render the notice and alert partials %>
      <%= render "layouts/partials/flash_messages" %>

    <%= render "layouts/partials/footer" %>
  </body>
</html>

5.Rails-Practices-Work/rails-esbuld-setup/app/views/layouts/partials/_container.html.erb
<div class="container-fluid mt-5">
    <div class="row">
    </div>
</div>

5.Rails-Practices-Work/rails-esbuld-setup/app/views/layouts/partials/_flash_messages.html.erb
<% if flash[:notice] %>
  <div class="alert alert-success alert-dismissible fade show mt-3" role="alert">
    <%= flash[:notice] %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% end %>

<% if flash[:alert] %>
  <div class="alert alert-danger alert-dismissible fade show mt-3" role="alert">
    <%= flash[:alert] %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% end %>

5.Rails-Practices-Work/rails-esbuld-setup/app/views/layouts/partials/_footer.html.erb
<!-- Footer Start -->
<div class="separator my-0">
<section class="footer">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                    <p class="text-center white">2020 © Kleo. All Rights Reserved.</p>
            </div>
        </div>
    </div>
</section>
</div>
<!-- Footer End -->

5.Rails-Practices-Work/rails-esbuld-setup/app/views/layouts/partials/_header.html.erb
<!-- Header Start -->
<section class="header-bg align-items-center position-relative d-flex" id="top">
    <div class="container">
        <div class="row align-items-center">
            <div class="col-lg-6">
                <div class="header-title">
                    <p class="highlight font-weight-bold size-16 text-uppercase header-small-title title mb-3 ml-1">Bootstrap Theme</p>
                    <h1 class="font-weight-bold main-title mb-4">Creating Bootstrap Theme From Scratch</h1>
                    <p class="text-sub ml-2 mb-4 pb-2">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. </p>
                    <a href="" class="btn btn-primary ml-2">Learn More <span class="ml-2 right-icon"><i class="fas fa-arrow-right"></i></span></a>
                </div>
            </div>
            <div class="col-lg-5 offset-lg-1">
                <div class="mt-5 mt-lg-0">
                    <img src="images/header-2.png" alt="" class="img-fluid mx-auto d-block">
                </div>
            </div>
        </div>
    </div>
</section>
<!-- Header End -->

5.Rails-Practices-Work/rails-esbuld-setup/app/views/layouts/partials/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">
      <%= image_tag 'rails_logo.png', alt: 'rails logo', style: 'width: 50px; height: 50px;' %>

    </a>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">

        <li class="nav-item">
          <%= link_to "Home", root_path, class: "nav-link active", aria: { current: "page" } %>
        </li>

        <li class="nav-item">
          <%= link_to "About", about_path, class: "nav-link" %>
        </li>

        <li class="nav-item">
          <%= link_to "Contact", contact_path, class: "nav-link" %>
        </li>

        <li class="nav-item">
          <%= link_to "Privacy", privacy_path, class: "nav-link" %>
        </li>

        <li class="nav-item">
          <%= link_to "Testimonials", testimonials_path, class: "nav-link" %>
        </li>


        <li class="nav-item">
          <%= link_to "Services", services_path, class: "nav-link" %>
        </li>

        <li class="nav-item">
          <%= link_to "Users", user_index_path, class: "nav-link" %>
        </li>


      </ul>

      <%# <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search"/>
        <button class="btn btn-outline-success pt-1 pb-1 ps-3 pe-3" type="submit">Search</button>
      </form> %>

    </div>
  </div>
</nav>

5.Rails-Practices-Work/rails-esbuld-setup/app/views/pages/about.html.erb
<!-- About Start -->
<section class="section bg-grey  mt-4" id="about">
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-lg-6 col-md-8">
        <div class="text-center mb-5">
          <h2 class="highlight header-colorize text-uppercase mb-3">About Us</h2>
          <p class="text-sub size-14">
            Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
          </p>
        </div>
      </div>
    </div>

    <div class="row align-items-center border mt-3 p-2">
      <div class="col-lg-5">
        <%= image_tag "person.jpg", class: "img-fluid mx-auto d-block w-50 h-50", alt: "About header image" %>
      </div>

      <div class="col-lg-6 offset-lg-0">
        <div class="text-sub mt-5 mt-lg-0">
          <h3 class="title font-weight-medium mb-4">A perfect bootstrap theme for all types of business.</h3>

          <p class="mb-4 size-15">
            Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam.
          </p>

          <p class="mb-4 size-15">
            Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos.
          </p>

          <a href="#" class="learn-more size-15">
            Learn more
            <span class="ml-2 right-icon">
              <i class="fas fa-arrow-right"></i>
            </span>
          </a>
        </div>
      </div>
    </div>
  </div>
</section>
<!-- About End -->

5.Rails-Practices-Work/rails-esbuld-setup/app/views/pages/contact.html.erb
<div class="container mt-4">
  <div class="form-container">
    <div class="left-container">
      <div class="left-inner-container">
      <h2>Let's Chat</h2>
      <p>Whether you have a question, want to start a project or            simply want to connect.</p>
        <br>
        <p>Feel free to send me a message in the contact form</p>
    </div>
      </div>
    <div class="right-container">
      <div class="right-inner-container">
        <form action="#">
			<h2 class="lg-view">Contact</h2>
      <h2 class="sm-view">Let's Chat</h2>
           <p>* Required</p>
			<div class="social-container">
				<a href="#" class="social"><i class="fab fa-facebook-f"></i></a>
				<a href="#" class="social"><i class="fab fa-google-plus-g"></i></a>
				<a href="#" class="social"><i class="fab fa-linkedin-in"></i></a>
			</div>
          <input type="text" placeholder="Name *"  />
      <input type="email" placeholder="Email *" />
			<input type="text" placeholder="Company" />
			<input type="phone" placeholder="Phone" />
          <textarea rows="4" placeholder="Message"></textarea>
			<button>Submit</button>
		</form>
      </div>
    </div>
  </div>
</div>

5.Rails-Practices-Work/rails-esbuld-setup/app/views/pages/index.html.erb
<div class="container mt-4">
    <div class="index-page">
        <%= render 'layouts/partials/header' %>
    </div>
</div>

5.Rails-Practices-Work/rails-esbuld-setup/app/views/pages/privacy.html.erb
<div class="privacy-page">
  <div class="privacy-container">
    <h1>Privacy Policy</h1>

    <section>
      <h2>1. Introduction</h2>
      <p>
        We are committed to protecting your personal information. This Privacy Policy
        explains how we collect, use, and secure the data you provide when using our website.
      </p>
    </section>

    <section>
      <h2>2. Information We Collect</h2>
      <p>
        We may collect personal information such as your name, email address, account data,
        and usage activity. This information helps us improve the quality and performance of our services.
      </p>
    </section>

    <section>
      <h2>3. How We Use Your Information</h2>
      <ul>
        <li>To provide and maintain our services</li>
        <li>To improve user experience</li>
        <li>To communicate updates or important notifications</li>
        <li>To ensure platform security and prevent misuse</li>
      </ul>
    </section>

    <section>
      <h2>4. Cookies & Tracking</h2>
      <p>
        We use cookies to enhance functionality and analyze site traffic. You may disable cookies
        in your browser settings, but some features may not work correctly.
      </p>
    </section>

    <section>
      <h2>5. Data Protection</h2>
      <p>
        Your data is stored securely, and we apply industry-standard measures to prevent unauthorized access,
        modification, or disclosure.
      </p>
    </section>

    <section>
      <h2>6. Your Rights</h2>
      <p>You have the right to access, modify, or delete your data at any time.</p>
    </section>

    <section>
      <h2>7. Contact Us</h2>
      <p>
        If you have any questions about this Privacy Policy, please contact us through our support page.
      </p>
    </section>
  </div>
</div>

5.Rails-Practices-Work/rails-esbuld-setup/app/views/pages/services.html.erb
<!-- Services Start -->
<section class="section py-5" id="services">
  <div class="container">

    <!-- Header -->
    <div class="row justify-content-center">
      <div class="col-lg-6 col-md-8 text-center mb-5">
        <h2 class="text-uppercase mb-3 highlight header-colorize">Our Services</h2>
        <p class="text-sub size-14">
          Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
        </p>
      </div>
    </div>

    <!-- Cards -->
    <div class="row g-4">

      <!-- Card 1 -->
      <div class="col-lg-4 col-md-6">
        <div class="card h-100 shadow-sm border-0">
          <div class="card-body text-center p-4">
            <div class="services-icon mb-3">
              <i class="far fa-window-maximize fa-3x text-primary"></i>
            </div>
            <h4 class="services-title mb-3">Web Design</h4>
            <p class="text-sub size-15">
              Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
            </p>
          </div>
        </div>
      </div>

      <!-- Card 2 -->
      <div class="col-lg-4 col-md-6">
        <div class="card h-100 shadow-sm border-0">
          <div class="card-body text-center p-4">
            <div class="services-icon mb-3">
              <i class="far fa-window-restore fa-3x text-primary"></i>
            </div>
            <h4 class="services-title mb-3">App Development</h4>
            <p class="text-sub size-15">
              Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
            </p>
          </div>
        </div>
      </div>

      <!-- Card 3 -->
      <div class="col-lg-4 col-md-6">
        <div class="card h-100 shadow-sm border-0">
          <div class="card-body text-center p-4">
            <div class="services-icon mb-3">
              <i class="fas fa-mobile-alt fa-3x text-primary"></i>
            </div>
            <h4 class="services-title mb-3">Mobile Development</h4>
            <p class="text-sub size-15">
              Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
            </p>
          </div>
        </div>
      </div>

    </div>
    <!-- End Cards -->

  </div>
</section>
<!-- Services End -->

5.Rails-Practices-Work/rails-esbuld-setup/app/views/pages/testimonials.html.erb
<!-- Testimonials Start -->
<section class="section bg-grey border border-b-black p-2 m-2" id="testimonials">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-lg-6 col-md-8">
                <div class="text-center mb-5">
                    <h2 class="highlight text-uppercase mb-3 header-colorize">Testimonials</h2>
                    <p class="text-sub size-14">Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
                </div>
            </div>
        </div>
 
        <div class="row">
            <div class="col-md-9 col-center m-auto">
 
 
            <div id="myCarousel" class="carousel slide" data-ride="carousel">
                <!-- Carousel indicators -->
                <ol class="carousel-indicators">
                    <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
                    <li data-target="#myCarousel" data-slide-to="1"></li>
                    <li data-target="#myCarousel" data-slide-to="2"></li>
                </ol>   
                <!-- Wrapper for carousel items -->
                <div class="carousel-inner">
                    <div class="item carousel-item active">
                        <div class="img-box"><img src="images/client.jpg" alt=""></div>
                        <p class="testimonial">"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam eu sem tempor, varius quam at, luctus dui. Mauris magna metus, dapibus nec turpis vel, semper malesuada ante. Idac bibendum scelerisque non non purus. Suspendisse varius nibh non aliquet."</p>
                        <p class="overview"><b>Kit Johnson</b>, Account Analyst</p>
                    </div>
                    <div class="item carousel-item">
                        <div class="img-box"><img src="images/client2.jpg" alt=""></div>
                        <p class="testimonial">"Vestibulum quis quam ut magna consequat faucibus. Pellentesque eget nisi a mi suscipit tincidunt. Utmtc tempus dictum risus. Pellentesque viverra sagittis quam at mattis. Suspendisse potenti. Aliquam sit amet gravida nibh, facilisis gravida odio."</p>
                        <p class="overview"><b>Rick Gomez</b>, App Developer</p>
                    </div>
                    <div class="item carousel-item">
                        <div class="img-box"><img src="images/client3.jpg" alt=""></div>
                        <p class="testimonial">"Phasellus vitae suscipit justo. Mauris pharetra feugiat ante id lacinia. Etiam faucibus mauris id tempor egestas. Duis luctus turpis at accumsan tincidunt. Phasellus risus risus, volutpat vel tellus ac, tincidunt fringilla massa. Etiam hendrerit dolor eget rutrum."</p>
                        <p class="overview"><b>Chris Smith</b>, CEO, ProTools</p>
                    </div>
                </div>
                <!-- Carousel controls -->
                <a class="carousel-control left carousel-control-prev" href="#myCarousel" data-slide="prev">
                    <i class="fa fa-angle-left"></i>
                </a>
                <a class="carousel-control right carousel-control-next" href="#myCarousel" data-slide="next">
                    <i class="fa fa-angle-right"></i>
                </a>
            </div>
    
        </div>
        
    </div>
</section>
<!-- Testimonials End -->