5.Rails-Practices-Work/simple-scaffold-practices/config/routes.rb
Rails.application.routes.draw do
  
  # available pages routes
  get "pages/index"
  get "pages/about"
  get "pages/contact"
  get "pages/privacy"
  get "pages/testimonials"
  get "pages/services"

end
0

5.Rails-Practices-Work/simple-scaffold-practices/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern

  # Changes to the importmap will invalidate the etag for HTML responses
  stale_when_importmap_changes
end

5.Rails-Practices-Work/simple-scaffold-practices/app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
    # render plain: "Can pass as plain text"   # as plain text
    # render template: "/directory/file"       # as template render
    # render "/directory/file" # as similar as template where specifying template is not mandatory

    # redirect_to some_path # redirect_to some path

    
  end

  def about
  end

  def contact
  end

  def privacy
  end
end

5.Rails-Practices-Work/simple-scaffold-practices/app/views/layouts/partials/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">
      <%= image_tag 'rails_logo.png', alt: 'rails logo', style: 'width: 50px; height: 50px;' %>

    </a>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">

        <li class="nav-item">
          <%= link_to "Home", pages_index_path, class: "nav-link active", aria: { current: "page" } %>
        </li>

        <li class="nav-item">
          <%= link_to "About", pages_about_path, class: "nav-link" %>
        </li>

        <li class="nav-item">
          <%= link_to "Contact", pages_contact_path, class: "nav-link" %>
        </li>

        <li class="nav-item">
          <%= link_to "Privacy", pages_privacy_path, class: "nav-link" %>
        </li>

        <li class="nav-item">
          <%= link_to "Testimonials", pages_testimonials_path, class: "nav-link" %>
        </li>


        <li class="nav-item">
          <%= link_to "Services", pages_services_path, class: "nav-link" %>
        </li>


      </ul>

      <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search"/>
        <button class="btn btn-outline-success p-2" type="submit">Search</button>
      </form>

    </div>
  </div>
</nav>